### ISSUE TITLE
hydra-router not processing application/x-www-form-urlencoded request 

### ISSUE THREAD

**Issue by malasgowda** [flywheelsports/hydra-router#123]
Hi ,

If post request is sent directly to hydra-express with content-type as application/x-www-form-urlencoded then we are able to get the request body, but if the same request is sent through hydra-router then request body is coming empty.

**Comment by cjus** [comment]
Hello @malasgowda Hydra-router doesn't currently support form submission. Your microservice is expected to accept JSON requests.

**Comment by zerefel** [comment]
Accepting JSON is mostly fine when working on a private API. However, some 3rd party services that offer webhook notifications send along 'application/x-www-form-urlencoded' content-type, which, in turn, fails at the hydra-router level.
