### ISSUE TITLE
"Overlapping" routes

### ISSUE THREAD

**Issue by mozrat** [flywheelsports/hydra-router#145]
Hi Carlos,

My envisioned design for my API URL structure isn't working out with hydra-router and looking at the code I think it might not be possible.

I have route registered with different microservices like so

```
{
  "ui-service": [
    "[get]/api/table/portal",
    "......"],
   "datastore-service": [
     "[get]/api/table/:tableName",
     "......."]
}
```

My intent was that all tables are handled by the datastore-service but I wanted to route requests for /api/table/portal to the ui-service

For users there would be one consistent API structure with no need to understand which service provides the data

In [service-router._matchRoute](https://github.com/flywheelsports/hydra-router/blob/master/servicerouter.js#L386) on line 386 I see that we iterate through the routes returning on the first matching route.

That doesn't seem to support my idea. Was just looking for confirmation and your thoughts

Thanks

**Comment by cjus** [comment]
I think you're right. As it stands HydraRouter and hydra, in general, expects routes to be in the form of `/v1/{serviceName}/{restOfRoutePath}`

**Comment by cjus** [comment]
@mozrat consider if this might be of help: https://github.com/jkyberneees/hydra-plugin-http

**Comment by mozrat** [comment]
@cjus Thank you - it's made me review the design and a microservice that aggregates a common namespace over the different services seems to be required, rather than trying to inject the microservice at different points of the route table.

I had considered a pull request to hydra-router to examine the route and to compare how deep it was, giving precedence to deeper routes - but I'd like to stay on the mainstream of the hydra project rather than doing something unusual
