### ISSUE TITLE
Routing not working

### ISSUE THREAD

**Issue by mkrishna2025** [flywheelsports/hydra-router#174]
I am getting below error ....

{"statusCode":404,"statusMessage":"Not Found","statusDescription":"The requested resource was not found on the server","result":{}}

**Comment by cjus** [comment]
@mkrishna2025 the error you're getting doesn't mean the routing isn't working. Actually, it means that it *is* working.  The bottom line is probably that your route isn't probably defined and/or being registered. Do you have any code you can share around that?

**Comment by mkrishna2025** [comment]
Thanks.. It is working..
