### ISSUE TITLE
queuer redis db shouldn't be hardcoded

### ISSUE THREAD

**Issue by emadum** [flywheelsports/hydra-router#93]
See here:

https://github.com/flywheelsports/hydra-router/blob/master/servicerouter.js#L73

@taurenk ran into this issue while using a RedisLabs redis instance, which only supports db 0.

**Comment by taurenk** [comment]
Submitted PR: https://github.com/flywheelsports/hydra-router/pull/96

**Comment by cjus** [comment]
Fixed by #96
