### ISSUE TITLE
Router doesn't correctly report service unavailable?

### ISSUE THREAD

**Issue by cjus** [flywheelsports/hydra-router#97]
It seems that when multiple service instances are no longer available, Hydra Router reports timeout rather than service unavailable.  Reported by @artemkochnev

**Comment by taurenk** [comment]
Just to add, the version of hydra-router we saw this issue in is `1.2.0`

**Comment by cjus** [comment]
@taurenk @artemkochnev It would be good if you guys can demo this. I wasn't able to recreate it this evening.

**Comment by cjus** [comment]
This is resolved in hydra-router:1.3.1
