### ISSUE TITLE
_handleRouterRequest allows access when no token is set

### ISSUE THREAD

**Issue by Sebastiansch** [flywheelsports/hydra-router#99]
Given the following configuration

`  "routerToken": "098ebe18-7e1b-4ddd-ae2a-cc6521e5b641",  "disableRouterEndpoint": false,`

will allow you to access routes, as long as you do not supply a token in request url.

http://localhost:5353/v1/router/list/routes => Route will be handled (BUG?)
http://localhost:5353/v1/router/list/routes?token=someinvalid =>  Route will be rejected (Working as intended)
http://localhost:5353/v1/router/list/routes?token=098ebe18-7e1b-4ddd-ae2a-cc6521e5b641 =>  Route will be handled (Working as intended)

**Comment by cjus** [comment]
Merged in https://github.com/flywheelsports/hydra-router/commit/807381fdca54ab469430d055e39c972eb355dd6b  Available in hydra-router:1.3.8
